### ISSUE TITLE
"App not installed as package appears to be invalid""

### ISSUE THREAD

**Issue by HiFiiDev** [Kyant2021/MYUI#1]
Hello, I am trying to compile this and getting the error in the title when trying to install. I have a rooted pixel for XL running the latest Android 12 beta.  Thanks and sorry if this is an easy issue to fix

**Comment by Kyant2021** [comment]
Try to add this line in gradle.properties.

`android.injected.testOnly=false`

**Comment by HiFiiDev** [comment]
Hey there,

The laptop I'm using is getting out of memory errors, I am Rusty but will report back as soon as i get it working

**Comment by HiFiiDev** [comment]
it worked!! thank you :)
